-keepattributes
-keep class * extends com.raizlabs.android.dbflow.config.DatabaseHolder { *; }
-dontpreverify
-dontoptimize
-dontobfuscate
-keep class dev.ukanth.ufirewall.** { *; }
-optimizations !code/allocation/variable
