#!/system/bin/sh

if [ -e /data/data/dev.ukanth.ufirewall/app_bin/iptables_armv5 ]
  then
    /data/data/dev.ukanth.ufirewall/app_bin/iptables_armv5 -P INPUT DROP
	/data/data/dev.ukanth.ufirewall/app_bin/iptables_armv5 -P OUTPUT DROP
	/data/data/dev.ukanth.ufirewall/app_bin/iptables_armv5 -P FORWARD DROP
fi;

# this is for donate users

if [ -e /data/data/dev.ukanth.ufirewall.donate/app_bin/iptables_armv5 ]
  then
    /data/data/dev.ukanth.ufirewall.donate/app_bin/iptables_armv5 -P INPUT DROP
	/data/data/dev.ukanth.ufirewall.donate/app_bin/iptables_armv5 -P OUTPUT DROP
	/data/data/dev.ukanth.ufirewall.donate/app_bin/iptables_armv5 -P FORWARD DROP
fi;



